name: Print Software Versions
on:
  push:
    branches: main 
jobs:
  PrintLanguageVersions:
    runs-on: ubuntu-latest
    steps:
      - name: Print Node.js Version
        run: node --version

  PrintDBMSVersions:
    runs-on: ubuntu-latest
    needs: [PrintLanguageVersions]
    steps:
      - name: Add Oracle APT Repository
        run: |
          sudo apt-get update
          sudo apt-get install -y wget gpg lsb-release
          wget -q -O - https://yum.oracle.com/RPM-GPG-KEY-oracle-2023 | sudo gpg --dearmor -o /usr/share/keyrings/oracle-yum-keyring.gpg
          echo "deb [signed-by=/usr/share/keyrings/oracle-yum-keyring.gpg] https://yum.oracle.com/apt/oracle-instantclient/ $(lsb_release -cs) main" | sudo tee /etc/apt/sources.list.d/oracle-instantclient.list
          sudo apt-get update
  
      - name: Install Oracle Instant Client
        run: |
          sudo apt-get install -y oracle-instantclient-sqlplus

      - name: Print Oracle Version
        run: sqlplus -V
