name: Print Software Versions
on:
  push:
    branches: main
jobs:
  PrintLanguageVersions:
    runs-on: ubuntu-latest
    steps:
      - name: Print Node.js Version
        run: node --version

  PrintDBMSVersions:
    runs-on: ubuntu-latest
    needs: [PrintLanguageVersions]
    steps:
      - name: Set up Oracle Instant Client
        uses: iamazeem/setup-oracle-instant-client-action@v2
 
      - name: Print Oracle Version
        run: sqlplus -V
