name: Print Software Versions
on:
  push:
    branches: main 

jobs:
  PrintLanguageVersions:
    name: Print Node.js Version
    runs-on: ubuntu-latest
    steps:
      - name: Print Node.js Version
        run: node --version

  PrintDBMSVersions:
    name: Print Oracle Client Version
    runs-on: ubuntu-latest
    needs: [PrintLanguageVersions]
    steps:
      - name: Setup Oracle Instant Client
        uses: oracle-actions/setup-instant-client@v1 
      - name: Print Oracle Client (SQL*Plus) Version
        run: sqlplus -V                     
